version: '3'
services:
    elk:
        image: sebp/elk
        volumes: 
            - /home/liyang/temp/elk-data:/var/lib/elasticsearch
            - /etc/localtime:/etc/localtime
        ports:  
            - 5601:5601 
            - 9200:9200 
            - 5044:5044 
        container_name: elk